research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

poem_task:
  description: >
    Review the context you got and expand each topic into a full section for a poem.
    Make sure the poem is detailed and contains any and all relevant information.
    Make sure the poem is written using a clear rhythm and rhymes.
  expected_output: >
    A fully fledged poem with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: poet
